FROM node:18-alpine AS build

WORKDIR /app

COPY frontend/ApplicantAura/package*.json ./
RUN npm install

COPY frontend/ApplicantAura ./
RUN npm run build

FROM nginx:1.25-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]








